### ISSUE TITLE
Issues related to projection

### ISSUE THREAD

**Issue by orange-416** [Qi-Yangsjtu/TMM2020#1]
Hello, I use the projection algorithm on the database you proposed(SJTU-PCQA). The algorithm runs successfully on most of the data, but when processing "hhi.ply", the following error is reported.

`错误使用 sub2ind (line 43)
下标超出范围。

出错 getProjection_image (line 100)
    map{i}(sub2ind(size(map{i}),datap(index{i},2),datap(index{i},1))) = datap(index{i},3);  % for quantization q2

出错 TMM_demo (line 17)
[image_d, map_d, ~, ~, ~, occupancy_d ] = getProjection_image( pt2);`

I wonder how you handled this situation?

**Comment by Qi-Yangsjtu** [comment]
The reason is that the resolution of the texture map is 1280*1280, I suggest to resize the coordinates of hhi.ply to [0,1280]

**Comment by orange-416** [comment]
> The reason is that the resolution of the texture map is 1280*1280, I suggest to resize the coordinates of hhi.ply to [0,1280]

Thank you for your kind reply.
 I use the down sampling method in the link ([https://www.cnblogs.com/tiandsp/p/10574530.html]) to scale the point cloud, but the error "数组超过预设的最大数组大小" still appears.
I'm trying to use this code to recalculate the objective score of the distorted point cloud, but I can't find your data processing in the experiment part of the article. Can you tell me how do you scale the point cloud? Or did you abandon PCs in the 1280 range? looking forward to your reply.

**Comment by Qi-Yangsjtu** [comment]
[inter.m.zip](https://github.com/Qi-Yangsjtu/TMM2020/files/9800326/inter.m.zip)
please use this function, and the scaling process is commended in the function getProjection_image, line 9: regularization, for hhi, the ii = 9 and the function utilization is xyz = inter(pt, 1, 780)

**Comment by orange-416** [comment]
> [inter.m.zip](https://github.com/Qi-Yangsjtu/TMM2020/files/9800326/inter.m.zip) please use this function, and the scaling process is commended in the function getProjection_image, line 9: regularization, for hhi, the ii = 9 and the function utilization is xyz = inter(pt, 1, 780)

It finally worked correctly. Thanks for your answer！
